### PR TITLE
[ISSUE #81]Fix RocketMQTemplate.syncSend collection type method signature

### PR DESCRIPTION
**Pull request by MartinDai**
## What is the purpose of the change

fix RocketMQTemplate.syncSend collection type method signature

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. 
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by RongtongJin** [comment]
Hi @MartinDai, do you verified in you environment? I tried your pr, but still the `syncSend(String destination, Object payload, long timeout)`  method was called.

**Comment by MartinDai** [comment]
> Hi @MartinDai, do you verified in your environment? I tried your pr, but still the `syncSend(String destination, Object payload, long timeout)` method was called.

I verified that it is ok.Can you provide your invoke this method's code segment?

**Comment by RongtongJin** [comment]
> > Hi @MartinDai, do you verified in your environment? I tried your pr, but still the `syncSend(String destination, Object payload, long timeout)` method was called.
> 
> I verified that it is ok.Can you provide your invoke this method's code segment?

OKay, It's success now. So why not just change the method signature to `SendResult syncSend(String destination, Collection<Message> messages, long timeout)`?

**Comment by MartinDai** [comment]
> > > Hi @MartinDai, do you verified in your environment? I tried your pr, but still the `syncSend(String destination, Object payload, long timeout)` method was called.
> > 
> > 
> > I verified that it is ok.Can you provide your invoke this method's code segment?
> 
> OKay, It's success now. So why not just change the method signature to `SendResult syncSend(String destination, Collection<Message> messages, long timeout)`?

Because ```SendResult syncSend(String destination, Collection<Message> messages, long timeout)``` means the ```messages```'s node type must be ```Message```(exclude subClass or implementation class), but Message is a interface, so that will be never invoked.

**Comment by RongtongJin** [comment]
@MartinDai, Got it, LGTM~

**Comment by vongosling** [comment]
@MartinDai It would be helpful to verify if you could add some test in your polish. I would like to follow up and help to merge this pr:-)

**Comment by MartinDai** [comment]
> @MartinDai It would be helpful to verify if you could add some test in your polish. I would like to follow up and help to merge this pr:-)

OK, I will add some test code soon.

**Comment by MartinDai** [comment]
@vongosling I was committed some test code,but the Travis CI build failed. I don't understand  the error detail, can you help to process?

**Comment by RongtongJin** [comment]
@MartinDai The reason for the failure of Travis CI may be the lack of Apache license in your newly created file. But more importantly, you should write some unit tests instead of sample.

**Comment by MartinDai** [comment]
@RongtongJin @vongosling I was added some unit test code,you can check it now.

**Comment by vongosling** [comment]
@MartinDai Just add some unit test to verify your modification instead of making the code more complex :-(

**Comment by RongtongJin** [comment]
@MartinDai Could you delete sample related code that you add ？We don't need a new sample.
In addition, the `testBatchSendMessage` test  that you add is failed in unit test.

**Comment by MartinDai** [comment]
@RongtongJin The unnecessary code was reverted, and the Travis CI build passed.It means the unit test was passed right?

**Comment by RongtongJin** [comment]
Good job, and the unit test was passed,  but even if choose the wrong type, it will also pass.
I think you can expect the exccption that only syncSend batch messages will throw.

**Comment by MartinDai** [comment]
@RongtongJin I have changed the `testBatchSendMessage ` unit test method.I think that is the best way for this🤣.

**Comment by RongtongJin** [comment]
LGTM~

**Comment by duhenglucky** [comment]
@MartinDai could you resolve the conflict first, and we will merge this PR ASAP.

**Comment by MartinDai** [comment]
> @MartinDai could you resolve the conflict first, and we will merge this PR ASAP.

Has done yet. You can merge now

**Pull request merged**
