### PR TITLE
[ISSUE #46] support multi rocketmq server

### PR DESCRIPTION
**Pull request by walkerzhao**
## What is the purpose of the change

* support consume multiple rocketmq srv and add multi producer demo.
* This issue:https://github.com/apache/rocketmq-spring/issues/46

## Brief changelog
* consume multiple rocket svr by set RocketMQMessageListener property namesrv and instanceName;
* add multiple producers to multiple rocketmq srv demo.

* Maybe in the future, the multiple producer  can be writen as spring datasource. That is more graceful.

## Verifying this change
* can verify consumer  by StringWithNamesrvConsumer;
* can verify producer by ProducerApplication.

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq-spring/issues/46) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. 
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by walkerzhao** [comment]
@walking98   hi kevin. Is there any response  about this merge?
Wish your review.

**Comment by walking98** [comment]
Hi,  the major scenario is to support consumer & producer using different name-server, it can be implemented by add an optional property for @RocketMQMessageListener, e.g.
@RocketMQMessageListener(nameServer = "${extra.consumer.name-server}", ...)

If we need more producer with different name-servers, I think it can be implemented by extra configuration, e.g.
@Component(name="extraProducerTemplate")
@ExtProducerConfigure(nameServer="",   以及如下的producer配置项，它们默认使用global的配置
     groupName="",
     aclAccessKey = "",
     aclSecretKey = "",
     enableMsgTrace = "",
     customizedTraceTopic = "",
    sendMsgTimeout = "",
     retryTimesWhenSendFailed = "",
     retryTimeWhenSendAsyncFailed = "",
    maxMessageSize = "",
    compressMsgBodyOverThreshold = "",
    retryNextServer = "" )

I would like to add a new PR for your review and discuss.

**Comment by walking98** [comment]
please review the new PR #56 @walkerzhao

**Comment by walkerzhao** [comment]
> please review the new PR #56 @walkerzhao

In my demo, I set the property of instanceName.

In my test I find that for the different rocket mq server will have the same instanceName(ip@pid) in one process.
This will make the mq client as the same.

You can see the problem as: https://blog.csdn.net/weixin_39047791/article/details/82858765.

What about your suggestions about this problem? I just add the set method for the call user.

**Comment by walking98** [comment]
I do think so, I also added the logic to set instanceName internally.  
ExtProducerResetConfiguration.java
           // Set instanceName same as the beanName
        mqProducer.setInstanceName(beanName);

DefaultRocketMQListenerContainer.java
    consumer.setInstanceName(this.name);

@walkerzhao

**Comment by ShannonDing** [comment]
PR #56 is picked, I will close this PR soon.

**Comment by walkerzhao** [comment]
@walking98 
Thanks your fix, I will try the new version in our prod environment. 

Maybe nexttime you can do more change on my pull request instead of creating a new pull request.
 If not that ,my commit is missing. It cost my serveral days about reading the source code and support this issue.

**Pull request closed without merging**
