### PR TITLE
Blocking startup when no nameServer is set  issue:#45

### PR DESCRIPTION
**Pull request by k631583871**
> ## What is the purpose of the change
> * Blocking startup when no nameServer is set
> * This issue:#45
> 
> ## Brief changelog
> * 当未设置 nameServer  阻止程序运行。并且启动 FailureAnalyzer 提示开发者错误
> 
> ## Verifying this change
> * 只要不设置 nameServer  就可以验证这一更改
> 
> Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.
> 
> * [x]  Make sure there is a [Github issue](https://github.com/apache/rocketmq-spring/issues/45) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
> * [x]  Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
> * [x]  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
> * [x]  Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist.
> * [x]  Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
> * [ ]  If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by k631583871** [comment]
@walking98  这个头一次给 apache 贡献代码，要有什么不足的地方，麻烦指出

**Comment by ShannonDing** [comment]
@k631583871 Could you please fix the conflicts?

**Comment by ShannonDing** [comment]
@k631583871 @walking98 Could you please check this PR again?

**Comment by walking98** [comment]
1. In my though, it just need a warning message to notice user that the key property (e.g. name-server) is not set and rocketmq beans will not created. The fix is nice to have feature but not necessary IMO. 
2. There are some places reformatted the code, pls keep them if they are not related to the new fix

**Comment by walking98** [comment]
@k631583871

**Comment by k631583871** [comment]
我这个push 并不是必须的，只是锦上添花。

我理解的starter是：只有开发者想要使用框架的时候才引入，并且在使用的starter的时候就应该正确的配置配置文件。

这个push 可以避免一些问题的发生：
1. 当未设置 nameServer 阻止程序运行，可以让开发者或运维人员第一时间发现问题，加快问题的解决。

**Comment by walking98** [comment]
你的理由也比较充分，这个改动会比较大地改动bean加载的条件和机制，这个我们再评估一下想个的场景。

**Comment by k631583871** [comment]
我暂时想到了如下场景
1. 当首次使用框架的时候，忘记写上配置文件或者写的配置文件错误的时候。
1. 从 2.0.0 版本升级到新版本的时候。
1. 在第一次部署项目的时候（使用Spring Cloud  Config或者是外部引入配置）。
@walking98

**Comment by walking98** [comment]
https://github.com/apache/rocketmq-spring/pull/69/files I propose this PR which only gives a warning message if no rocketmq.name-server is defined. any comments? @k631583871

**Comment by k631583871** [comment]
很抱歉，这么久才回您。我看您的处理方式，也是一个很好的解决方案。
我也比较了这两种处理方案。我个人觉两个方案都很好没有对错，只是两种不同的处理方式。
我个人还是比较喜欢我自己这个解决方案。
@walking98 您要是觉得这个问题还有讨论下去的必要的话，我就把这个Pull requests开着。
要是您觉得没有必要话 ，我就close and comment。

**Comment by walking98** [comment]
好的，我建议使用warning的方式提示一下用户吧，如果要求nameserver强制设置对整个逻辑改动比较大。如果你愿意可以先关闭这个issue.

**Pull request closed without merging**
