### PR TITLE
[ISSUE#21] Support both spring-boot 1.X and 2.X

### PR DESCRIPTION
**Pull request by walking98**
## What is the purpose of the change

support both spring-boot 1.X and 2.X

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. 
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by vongosling** [comment]
@snicoll I am not sure It this an advisable way to be compatible with the spring boot 1.x :-)

**Comment by snicoll** [comment]
@vongosling Spring Boot 1.x will be EOL next August so I am not sure you should bother with it really. Having an integration with Spring Boot 2 only looks perfectly fine to me.

**Comment by vongosling** [comment]
@snicoll Your words really hit my thoughts, thanks:-) I also consider it is a good start to be with Spring Boot 2. @walking98

**Comment by walking98** [comment]
> @vongosling Spring Boot 1.x will be EOL next August so I am not sure you should bother with it really. Having an integration with Spring Boot 2 only looks perfectly fine to me.

wow, it might be a little bit hurt for customers who are using spring boot 1.x, if they want to use the new rocketmq-spring but not upgrade to spring boot/spring 5 at present.

**Comment by snicoll** [comment]
@walking98 I am not sure what you mean. Spring Boot `1.x` is in maintenance mode for quite some time now and customers will have to upgrade by August as it won't be officially supported by then. It really isn't about this project IMO and since you've released a version that starts with Spring Boot 2, expectations are quite clear and don't need to change.

**Comment by walking98** [comment]
ok, I meant the project ever used spring-boot 1.x an previous incubator phase. Some customers had tried to use it.   

anyway, I agree with the suggestion for supporting 2.x only.

**Pull request closed without merging**
