### PR TITLE
[ISSUE #104] Unable to support payload with byte[] type in methods with payload such as 'syncSend(String destination, Object payload)' #104

### PR DESCRIPTION
**Pull request by lemonzone2010**
support payload with byte[] type in methods with payload such as 'syncSend(String destination, Object payload)' #104

### CODE REVIEW

**Comment by RongtongJin** [comment]
LGTM~

**Comment by vongosling** [comment]
@lemonzone2010 Could you help to add unit test to coverage your polish:-)

**Comment by RongtongJin** [comment]
#152 had solved the issue.

**Comment by vongosling** [comment]
I will close the pr, and link up the two related pr to fix the bug and polish the code.

**Pull request closed without merging**
